### ISSUE TITLE
FileNotFoundError at subprocess

### ISSUE THREAD

**Issue by AsalJalilvand** [LoLei/spmf-py#1]
Hello Sir, 
Thank you very much for writing this wrapper. 
I have an issue running the program, I would appreciate it if you helped me fix it.
I face a problem at the run function. Here is the log:

File "C:\ProgramData\Miniconda3\envs\vaenv\lib\site-packages\spmf\__init__.py", line 102, in run
    proc = subprocess.check_output(subprocess_arguments)
  File "C:\ProgramData\Miniconda3\envs\vaenv\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Miniconda3\envs\vaenv\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Miniconda3\envs\vaenv\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Miniconda3\envs\vaenv\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Here is an example of how I run the program from example.py (spfm.jar and the input file are both in the same directory as the example.py)

```python
spmf_jar_dir = pathlib.Path(__file__).parent.absolute()

spmf = Spmf("PrefixSpan", input_filename="contextPrefixSpan.txt",spmf_bin_location_dir=spmf_jar_dir,
            output_filename="output.txt", arguments=[1, "", True])
spmf.run()
```
Here is what the variable status at line 102 of __init__.py
![Capture](https://user-images.githubusercontent.com/64210951/89080970-b548f500-d360-11ea-85a0-3585ecde8120.PNG)

I've also tried with the absolute path of the input file, but got the same error.

**Comment by LoLei** [comment]
I cannot reproduce this using your code on my system (Linux).

```
me@keyboard /tmp/spmf-test
$ ls -1
contextPrefixSpan.txt
spmf.jar
test.py
```

```python
from spmf import Spmf
import pathlib

spmf_jar_dir = pathlib.Path(__file__).parent.absolute()

spmf = Spmf("PrefixSpan",
            input_filename="contextPrefixSpan.txt",
            spmf_bin_location_dir=spmf_jar_dir,
            output_filename="output.txt", arguments=[1, "", True])
spmf.run()
```

```
$ python3 test.py
>/tmp/spmf-test/spmf.jar
=============  PREFIXSPAN 0.99-2016 - STATISTICS =============
 Total time ~ 2 ms
 Frequent sequences count : 5
 Max memory (mb) : 8.822776794433594
 minsup = 4 sequences.
 Pattern count : 5
===================================================
```

A few ideas:
* Can you try running the `java` command in your Windows command line? 
  * (`java -jar <your_path>spmf.jar run PrefixSpan contextPrefixSpan.txt output.txt 1 "" True`)
  * This is the same command Python tries to execute in your code.
  * It might not be able to find your *java* executable, not the `jar` file.
* You mention "spfm.jar". I hope that's just a typo here and your file isn't actually called that.

**Comment by AsalJalilvand** [comment]
Hi,
the problem was the java executable, thank you for replying.
