### ISSUE TITLE
Gives different output when tested on other algorithm

### ISSUE THREAD

**Issue by Choneke** [LoLei/spmf-py#2]
Thank you very much for this repo. It is very useful and helpful.
But when I use it in ToPKClass rule, the output which I get for any number of K (boundary for the number of rule to be generated) is 2. But when I run in jar file with the same input parameter the output which I expected is what I get. Are there any means to modify this?

**Comment by LoLei** [comment]
Interesting, thanks for reporting. spmf-py is largely untested for algorithms other than sequential pattern mining, such as association rule mining, although in theory the wrapper should work the same.

Could you please post the calls you make to both spmf-py and the jar itself, so I can reproduce it?

**Comment by Choneke** [comment]
I tried to run this on spmf-py

spmf = Spmf("TopKClassRules", input_filename="Input.txt",
            output_filename="output.txt", arguments=[10, 0.05, 1, 101, 2])

**Comment by LoLei** [comment]
Could you also post how you call the jar itself?

**Comment by Choneke** [comment]
This is how jar is called in __init__.py file which is under spmf folder.

```
class Spmf:
    def __init__(self,
                 algorithm_name,
                 input_direct=None,
                 input_type="normal",
                 input_filename="",
                 output_filename="spmf-output.txt",
                 arguments=[],
                 spmf_bin_location_dir=".",
                 memory=0):
        self.executable_dir_ = spmf_bin_location_dir
        self.executable_ = "spmf.jar"
```

And below picture shows how the file is arranged, and I run example2.py to get my output


![image](https://user-images.githubusercontent.com/39613742/95668535-4da8f480-0bb0-11eb-91ba-60574d194d2e.png)

**Comment by LoLei** [comment]
Thanks, but I was thinking about this:
>But when I run in jar file with the same input parameter the output which I expected is what I get.

Am I not understanding it correctly? That you also ran the spmf.jar file without spmf-py to get the correct output? I'm interested in that call.
